title: RealUI
tagline: Interface suite for World of Warcraft
description: "Interface suite for World of Warcraft"
url: https://github.com/RealUI
baseurl: /

author:
  name: 'Gethe'
  url: https://twitter.com/gethe88

excerpt_separator: <!--more-->
paginate: 5

exclude: []
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

version: 1.0.0

github:
  repo: https://github.com/RealUI/RealUI

# GitHub defaults - not configurable
#lsi: false
safe: true
#source: .
#incremental: false
#highlighter: rouge
gist:
  noscript: false
