title: RealUI
description: "Interface suite for World of Warcraft"
url: https://github.com/RealUI
baseurl: /

repository: RealUI/RealUI.github.io
exclude: [README.md, Gemfile, Gemfile.lock, serve.bat]
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-feed

email: realuiwow@gmail.com
twitter_username: realuiwow
github_username: RealUI
feed:
  path: atom.xml

# GitHub defaults - configurable
# github: [metadata]
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# theme: jekyll-theme-primer
# gfm_quirks: paragraph_end

# GitHub defaults - not configurable
lsi: false
safe: true
source: .
#incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
