title: RealUI
tagline: Interface suite for World of Warcraft
description: "Interface suite for World of Warcraft"
url: https://github.com/RealUI
baseurl: /
version: 1.0.0

author:
  name: 'RealUI'
  url: https://twitter.com/realuiwow

excerpt_separator: <!--more-->
paginate: 5

repository: RealUI/RealUI.github.io
exclude: [README.md, Gemfile, Gemfile.lock, serve.bat]
theme: jekyll-theme-midnight

# GitHub defaults - configurable
# github: [metadata]
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# theme: jekyll-theme-primer
# gfm_quirks: paragraph_end

# GitHub defaults - not configurable
lsi: false
safe: true
source: .
#incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
